apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: dotnet8-template
  title: Dotnet 8 Template
  description: Scaffold a new .NET 8 project
  tags:
    - dotnet
    - csharp
    - webapi
    - recommended
spec:
  owner: NikolasSantofimio
  type: service
  parameters:
    - title: Complete the form to create a new .NET 8 project
      required:
        - name
        - description
        - system
      properties:
        name:
          type: string
          title: Project Name
          description: The name of the project
        description:
          title: Description
          type: string
          description: A description for the component
        owner:
          title: Select in which group the component will be created
          type: string
          description: The group the component belongs to
        system:
          title: System
          type: string
          description: The system the component belongs to
    - title: Choose a destination
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository URL
          type: string
          description: The URL of the repository
  steps:
    - id: fetch-base
      name: Fetch Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutTemplating:
          - .github/workflows/*
        values:
          name: ${{ parameters.name }}
          owner: ${{ parameters.owner }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          repoUrl: ${{ parameters.repoUrl }}
          system: ${{ parameters.system }}

    - id: create-readme
      name: Create a README file
      action: fs:write
      input:
        files:
          - path: README.md
            contents: |
              # ${{ parameters.name }}
              ${{ parameters.description }}

              This is a new .NET 8 project created with 💚 using Backstage.

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
        # repoVisibility: private
        gitCommitMessage: Create scaffold
        topics: ["backstage-include", "returngis"]
        defaultBranch: main
        secrets: { MY_SECRET: This is a secret }
        variables: { MY_VARIABLE: This is a variable }

    - id: github:ghas:configure
      name: Configure GitHub Advanced Security
      action: github:ghas:configure
      input:
        repoUrl: ${{ parameters.repoUrl }}
        code_scanning: enabled
        secret_scanning: enabled
        push_secret_protection: enabled
        dependabot: enabled

    - id: github-action
      name: Stating GitHub action
      action: github:actions:dispatch
      input:
        workflowId: ci.yml
        repoUrl: ${{ parameters.repoUrl }}
        branchOrTagName: "main"

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
